export const DEVELOPMENT_SKILLS = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "Python",
  "C",
  "C++",
  "Java",
  "C#",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "Go",
  "Rust",
  "Dart",
  "R",
  "Perl",
  "Scala",
  "SQL",
  "NoSQL",
  "Bash",
  "Shell Scripting",
  "React.js",
  "Vue.js",
  "Angular",
  "Next.js",
  "Nuxt.js",
  "Node.js",
  "Express.js",
  "Tailwind CSS",
  "Bootstrap",
  "SASS",
  "LESS",
  "MongoDB",
  "PostgreSQL",
  "GraphQL",
  "REST API",
  "Git",
  "GitHub",
  "Redux",
  "Zustand",
  "MobX",
  "RTK Query",
  "TanStack Query",
  "Docker",
  "Kubernetes",
  "AWS",
  "Firebase",
  "Heroku",
  "Vercel",
  "Netlify",
  "Webpack",
  "Vite",
  "Gulp",
  "Jest",
  "Cypress",
  "Mocha",
  "Chai",
  "Framer Motion",
  "Shadcn UI",
  "Material-UI",
  "Chakra UI",
  "Emotion",
  "Styled Components",
  "WebSockets",
  "OAuth",
  "JWT",
  "Serverless",
  "Microservices",
  "RabbitMQ",
  "Elasticsearch",
  "Redis",
  "Prisma",
  "Mongoose",
  "Zod",
  "Formik",
  "Yup",
  "Clerk",
  "Auth0",
  "Puppeteer",
  "Headless CMS",
  "WordPress",
  "Jira",
  "Trello",
  "Figma",
  "Adobe XD",
];

export const DESIGN_SKILLS = [
  "Wireframing",
  "Prototyping",
  "User Research",
  "User Personas",
  "User Flows",
  "Information Architecture",
  "Interaction Design",
  "Visual Design",
  "Responsive Design",
  "Design Systems",
  "Accessibility",
  "Usability Testing",
  "A/B Testing",
  "Sketching",
  "Typography",
  "Color Theory",
  "Iconography",
  "Storyboarding",
  "Design Thinking",
  "Empathy Mapping",
  "Journey Mapping",
  "Heuristic Evaluation",
  "Brand Identity",
  "Layout Design",
  "Print Design",
  "Illustration",
  "Photo Editing",
  "Image Manipulation",
  "Vector Art",
  "Grid Systems",
  "Packaging Design",
  "Motion Graphics",
  "3D Design",
  "Visual Hierarchy",
  "Microinteractions",
  "Mockups",
  "Infographic Design",
  "Poster Design",
  "Brochure Design",
  "Advertising Design",
  "Video Editing",
  "Logo Design",
  "Typography Pairing",
  "Print Production",
  "Die-Cutting",
];

export const MARKETING_SKILLS = [
  "Content Marketing",
  "SEO",
  "SEM",
  "Email Marketing",
  "Social Media Marketing",
  "Influencer Marketing",
  "PPC Advertising",
  "Affiliate Marketing",
  "Copywriting",
  "Brand Strategy",
  "Market Research",
  "Customer Segmentation",
  "Lead Generation",
  "CRO",
  "Google Analytics",
  "Data Analysis",
  "A/B Testing",
  "Marketing Automation",
  "CRM",
  "Growth Hacking",
  "Product Marketing",
  "Public Relations",
  "Event Marketing",
  "Content Strategy",
  "Influencer Outreach",
  "Community Management",
  "Video Marketing",
  "Mobile Marketing",
  "E-commerce Marketing",
  "Retargeting",
  "Digital Advertising",
  "UX Writing",
  "Podcast Marketing",
  "Webinars",
  "Press Releases",
  "Google Ads",
  "Facebook Ads",
  "Instagram Ads",
  "LinkedIn Ads",
  "YouTube Ads",
  "Twitter Ads",
  "TikTok Marketing",
  "Ahrefs",
  "HubSpot",
  "SEMrush",
  "WordPress",
  "Buffer",
  "Mailchimp",
  "Hootsuite",
];
